/*
 * finAPI RESTful Services
 * finAPI RESTful Services
 *
 * OpenAPI spec version: v1.64.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * ClearingAccountData
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-02-05T12:19:21.458Z")
public class ClearingAccountData {
  @SerializedName("clearingAccountId")
  private String clearingAccountId = null;

  @SerializedName("clearingAccountName")
  private String clearingAccountName = null;

  public ClearingAccountData clearingAccountId(String clearingAccountId) {
    this.clearingAccountId = clearingAccountId;
    return this;
  }

   /**
   * Technical identifier of the clearing account
   * @return clearingAccountId
  **/
  @ApiModelProperty(example = "BA-TUYEF7D24CGK6", required = true, value = "Technical identifier of the clearing account")
  public String getClearingAccountId() {
    return clearingAccountId;
  }

  public void setClearingAccountId(String clearingAccountId) {
    this.clearingAccountId = clearingAccountId;
  }

  public ClearingAccountData clearingAccountName(String clearingAccountName) {
    this.clearingAccountName = clearingAccountName;
    return this;
  }

   /**
   * Name of the clearing account
   * @return clearingAccountName
  **/
  @ApiModelProperty(example = "BA-TUYEF7D24CGK6", required = true, value = "Name of the clearing account")
  public String getClearingAccountName() {
    return clearingAccountName;
  }

  public void setClearingAccountName(String clearingAccountName) {
    this.clearingAccountName = clearingAccountName;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ClearingAccountData clearingAccountData = (ClearingAccountData) o;
    return Objects.equals(this.clearingAccountId, clearingAccountData.clearingAccountId) &&
        Objects.equals(this.clearingAccountName, clearingAccountData.clearingAccountName);
  }

  @Override
  public int hashCode() {
    return Objects.hash(clearingAccountId, clearingAccountName);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ClearingAccountData {\n");
    
    sb.append("    clearingAccountId: ").append(toIndentedString(clearingAccountId)).append("\n");
    sb.append("    clearingAccountName: ").append(toIndentedString(clearingAccountName)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

