/*
 * finAPI RESTful Services
 * finAPI RESTful Services
 *
 * OpenAPI spec version: v1.20.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.InlineResponse2002Paging;
import io.swagger.client.model.InlineResponse2005Bank;
import java.util.ArrayList;
import java.util.List;

/**
 * Container for banks with paging info
 */
@ApiModel(description = "Container for banks with paging info")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-05-17T14:26:47.047Z")
public class InlineResponse2006 {
  @SerializedName("banks")
  private List<InlineResponse2005Bank> banks = new ArrayList<InlineResponse2005Bank>();

  @SerializedName("paging")
  private InlineResponse2002Paging paging = null;

  public InlineResponse2006 banks(List<InlineResponse2005Bank> banks) {
    this.banks = banks;
    return this;
  }

  public InlineResponse2006 addBanksItem(InlineResponse2005Bank banksItem) {
    this.banks.add(banksItem);
    return this;
  }

   /**
   * Banks data
   * @return banks
  **/
  @ApiModelProperty(example = "null", required = true, value = "Banks data")
  public List<InlineResponse2005Bank> getBanks() {
    return banks;
  }

  public void setBanks(List<InlineResponse2005Bank> banks) {
    this.banks = banks;
  }

  public InlineResponse2006 paging(InlineResponse2002Paging paging) {
    this.paging = paging;
    return this;
  }

   /**
   * Get paging
   * @return paging
  **/
  @ApiModelProperty(example = "null", value = "")
  public InlineResponse2002Paging getPaging() {
    return paging;
  }

  public void setPaging(InlineResponse2002Paging paging) {
    this.paging = paging;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse2006 inlineResponse2006 = (InlineResponse2006) o;
    return Objects.equals(this.banks, inlineResponse2006.banks) &&
        Objects.equals(this.paging, inlineResponse2006.paging);
  }

  @Override
  public int hashCode() {
    return Objects.hash(banks, paging);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse2006 {\n");
    
    sb.append("    banks: ").append(toIndentedString(banks)).append("\n");
    sb.append("    paging: ").append(toIndentedString(paging)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

