/*
 * finAPI RESTful Services
 * finAPI RESTful Services
 *
 * OpenAPI spec version: v1.20.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.InlineResponse20012Labels;
import io.swagger.client.model.InlineResponse2002Paging;
import java.util.ArrayList;
import java.util.List;

/**
 * Label resources with paging information
 */
@ApiModel(description = "Label resources with paging information")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-05-17T14:26:47.047Z")
public class PageableLabelList {
  @SerializedName("labels")
  private List<InlineResponse20012Labels> labels = new ArrayList<InlineResponse20012Labels>();

  @SerializedName("paging")
  private InlineResponse2002Paging paging = null;

  public PageableLabelList labels(List<InlineResponse20012Labels> labels) {
    this.labels = labels;
    return this;
  }

  public PageableLabelList addLabelsItem(InlineResponse20012Labels labelsItem) {
    this.labels.add(labelsItem);
    return this;
  }

   /**
   * Data of labels
   * @return labels
  **/
  @ApiModelProperty(example = "null", required = true, value = "Data of labels")
  public List<InlineResponse20012Labels> getLabels() {
    return labels;
  }

  public void setLabels(List<InlineResponse20012Labels> labels) {
    this.labels = labels;
  }

  public PageableLabelList paging(InlineResponse2002Paging paging) {
    this.paging = paging;
    return this;
  }

   /**
   * Get paging
   * @return paging
  **/
  @ApiModelProperty(example = "null", value = "")
  public InlineResponse2002Paging getPaging() {
    return paging;
  }

  public void setPaging(InlineResponse2002Paging paging) {
    this.paging = paging;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PageableLabelList pageableLabelList = (PageableLabelList) o;
    return Objects.equals(this.labels, pageableLabelList.labels) &&
        Objects.equals(this.paging, pageableLabelList.paging);
  }

  @Override
  public int hashCode() {
    return Objects.hash(labels, paging);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PageableLabelList {\n");
    
    sb.append("    labels: ").append(toIndentedString(labels)).append("\n");
    sb.append("    paging: ").append(toIndentedString(paging)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

