/*
 * finAPI RESTful Services
 * finAPI RESTful Services
 *
 * OpenAPI spec version: v1.64.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.Paging;
import io.swagger.client.model.Transaction;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

/**
 * Container for a page of transactions, with data about the total count of transactions and their balance
 */
@ApiModel(description = "Container for a page of transactions, with data about the total count of transactions and their balance")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-02-05T12:19:21.458Z")
public class PageableTransactionList {
  @SerializedName("transactions")
  private List<Transaction> transactions = new ArrayList<Transaction>();

  @SerializedName("paging")
  private Paging paging = null;

  @SerializedName("income")
  private BigDecimal income = null;

  @SerializedName("spending")
  private BigDecimal spending = null;

  @SerializedName("balance")
  private BigDecimal balance = null;

  public PageableTransactionList transactions(List<Transaction> transactions) {
    this.transactions = transactions;
    return this;
  }

  public PageableTransactionList addTransactionsItem(Transaction transactionsItem) {
    this.transactions.add(transactionsItem);
    return this;
  }

   /**
   * Array of transactions (for the requested page)
   * @return transactions
  **/
  @ApiModelProperty(required = true, value = "Array of transactions (for the requested page)")
  public List<Transaction> getTransactions() {
    return transactions;
  }

  public void setTransactions(List<Transaction> transactions) {
    this.transactions = transactions;
  }

  public PageableTransactionList paging(Paging paging) {
    this.paging = paging;
    return this;
  }

   /**
   * Information for pagination
   * @return paging
  **/
  @ApiModelProperty(required = true, value = "Information for pagination")
  public Paging getPaging() {
    return paging;
  }

  public void setPaging(Paging paging) {
    this.paging = paging;
  }

  public PageableTransactionList income(BigDecimal income) {
    this.income = income;
    return this;
  }

   /**
   * The total income of all transactions (across all pages)
   * @return income
  **/
  @ApiModelProperty(required = true, value = "The total income of all transactions (across all pages)")
  public BigDecimal getIncome() {
    return income;
  }

  public void setIncome(BigDecimal income) {
    this.income = income;
  }

  public PageableTransactionList spending(BigDecimal spending) {
    this.spending = spending;
    return this;
  }

   /**
   * The total spending of all transactions (across all pages)
   * @return spending
  **/
  @ApiModelProperty(required = true, value = "The total spending of all transactions (across all pages)")
  public BigDecimal getSpending() {
    return spending;
  }

  public void setSpending(BigDecimal spending) {
    this.spending = spending;
  }

  public PageableTransactionList balance(BigDecimal balance) {
    this.balance = balance;
    return this;
  }

   /**
   * The total sum of all transactions (across all pages)
   * @return balance
  **/
  @ApiModelProperty(required = true, value = "The total sum of all transactions (across all pages)")
  public BigDecimal getBalance() {
    return balance;
  }

  public void setBalance(BigDecimal balance) {
    this.balance = balance;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PageableTransactionList pageableTransactionList = (PageableTransactionList) o;
    return Objects.equals(this.transactions, pageableTransactionList.transactions) &&
        Objects.equals(this.paging, pageableTransactionList.paging) &&
        Objects.equals(this.income, pageableTransactionList.income) &&
        Objects.equals(this.spending, pageableTransactionList.spending) &&
        Objects.equals(this.balance, pageableTransactionList.balance);
  }

  @Override
  public int hashCode() {
    return Objects.hash(transactions, paging, income, spending, balance);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PageableTransactionList {\n");
    
    sb.append("    transactions: ").append(toIndentedString(transactions)).append("\n");
    sb.append("    paging: ").append(toIndentedString(paging)).append("\n");
    sb.append("    income: ").append(toIndentedString(income)).append("\n");
    sb.append("    spending: ").append(toIndentedString(spending)).append("\n");
    sb.append("    balance: ").append(toIndentedString(balance)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

