/*
 * finAPI RESTful Services
 * finAPI RESTful Services
 *
 * OpenAPI spec version: v1.20.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;

/**
 * Update specific transactions parameters
 */
@ApiModel(description = "Update specific transactions parameters")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-05-17T14:26:47.047Z")
public class UpdateMultipleTransactionsParams {
  @SerializedName("isNew")
  private Boolean isNew = false;

  @SerializedName("isPotentialDuplicate")
  private Boolean isPotentialDuplicate = false;

  @SerializedName("categoryId")
  private Long categoryId = null;

  @SerializedName("labelIds")
  private List<Long> labelIds = new ArrayList<Long>();

  @SerializedName("ids")
  private List<Long> ids = new ArrayList<Long>();

  @SerializedName("accountIds")
  private List<Long> accountIds = new ArrayList<Long>();

  public UpdateMultipleTransactionsParams isNew(Boolean isNew) {
    this.isNew = isNew;
    return this;
  }

   /**
   * Whether this transactions should be flagged as 'new' or not. Any newly imported transaction will have this flag initially set to true. How you use this field is up to your interpretation. For example, you might want to set it to false once a user has clicked on/seen the transaction.
   * @return isNew
  **/
  @ApiModelProperty(example = "null", value = "Whether this transactions should be flagged as 'new' or not. Any newly imported transaction will have this flag initially set to true. How you use this field is up to your interpretation. For example, you might want to set it to false once a user has clicked on/seen the transaction.")
  public Boolean getIsNew() {
    return isNew;
  }

  public void setIsNew(Boolean isNew) {
    this.isNew = isNew;
  }

  public UpdateMultipleTransactionsParams isPotentialDuplicate(Boolean isPotentialDuplicate) {
    this.isPotentialDuplicate = isPotentialDuplicate;
    return this;
  }

   /**
   * You can set this field only to 'false'. finAPI marks transactions as a potential duplicates  when its internal duplicate detection algorithm is signaling so. Transactions that are flagged as duplicates can be deleted by the user. To prevent the user from deleting original transactions, which might lead to incorrect balances, it is not possible to manually set this flag to 'true'.
   * @return isPotentialDuplicate
  **/
  @ApiModelProperty(example = "null", value = "You can set this field only to 'false'. finAPI marks transactions as a potential duplicates  when its internal duplicate detection algorithm is signaling so. Transactions that are flagged as duplicates can be deleted by the user. To prevent the user from deleting original transactions, which might lead to incorrect balances, it is not possible to manually set this flag to 'true'.")
  public Boolean getIsPotentialDuplicate() {
    return isPotentialDuplicate;
  }

  public void setIsPotentialDuplicate(Boolean isPotentialDuplicate) {
    this.isPotentialDuplicate = isPotentialDuplicate;
  }

  public UpdateMultipleTransactionsParams categoryId(Long categoryId) {
    this.categoryId = categoryId;
    return this;
  }

   /**
   * Identifier of the new category to apply to the transaction. When updating the transaction's category, the category's fields 'id', 'name', 'parentId', 'parentName', and 'isCustom' will all get updated. To clear the category for the transaction, the categoryId field must be passed with value 0.
   * @return categoryId
  **/
  @ApiModelProperty(example = "null", value = "Identifier of the new category to apply to the transaction. When updating the transaction's category, the category's fields 'id', 'name', 'parentId', 'parentName', and 'isCustom' will all get updated. To clear the category for the transaction, the categoryId field must be passed with value 0.")
  public Long getCategoryId() {
    return categoryId;
  }

  public void setCategoryId(Long categoryId) {
    this.categoryId = categoryId;
  }

  public UpdateMultipleTransactionsParams labelIds(List<Long> labelIds) {
    this.labelIds = labelIds;
    return this;
  }

  public UpdateMultipleTransactionsParams addLabelIdsItem(Long labelIdsItem) {
    this.labelIds.add(labelIdsItem);
    return this;
  }

   /**
   * Identifiers of labels to apply to the transaction. To clear transactions' labels, pass an empty array of identifiers: '[]'
   * @return labelIds
  **/
  @ApiModelProperty(example = "null", value = "Identifiers of labels to apply to the transaction. To clear transactions' labels, pass an empty array of identifiers: '[]'")
  public List<Long> getLabelIds() {
    return labelIds;
  }

  public void setLabelIds(List<Long> labelIds) {
    this.labelIds = labelIds;
  }

  public UpdateMultipleTransactionsParams ids(List<Long> ids) {
    this.ids = ids;
    return this;
  }

  public UpdateMultipleTransactionsParams addIdsItem(Long idsItem) {
    this.ids.add(idsItem);
    return this;
  }

   /**
   * A comma-separated list of transaction identifiers. If specified, then only transactions whose identifier match any of the given identifiers will be regarded. The maximum number of identifiers is 100.
   * @return ids
  **/
  @ApiModelProperty(example = "null", value = "A comma-separated list of transaction identifiers. If specified, then only transactions whose identifier match any of the given identifiers will be regarded. The maximum number of identifiers is 100.")
  public List<Long> getIds() {
    return ids;
  }

  public void setIds(List<Long> ids) {
    this.ids = ids;
  }

  public UpdateMultipleTransactionsParams accountIds(List<Long> accountIds) {
    this.accountIds = accountIds;
    return this;
  }

  public UpdateMultipleTransactionsParams addAccountIdsItem(Long accountIdsItem) {
    this.accountIds.add(accountIdsItem);
    return this;
  }

   /**
   * A comma-separated list of account identifiers. If specified, then only transactions whose account's identifier is included in this list will be regarded.
   * @return accountIds
  **/
  @ApiModelProperty(example = "null", value = "A comma-separated list of account identifiers. If specified, then only transactions whose account's identifier is included in this list will be regarded.")
  public List<Long> getAccountIds() {
    return accountIds;
  }

  public void setAccountIds(List<Long> accountIds) {
    this.accountIds = accountIds;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UpdateMultipleTransactionsParams updateMultipleTransactionsParams = (UpdateMultipleTransactionsParams) o;
    return Objects.equals(this.isNew, updateMultipleTransactionsParams.isNew) &&
        Objects.equals(this.isPotentialDuplicate, updateMultipleTransactionsParams.isPotentialDuplicate) &&
        Objects.equals(this.categoryId, updateMultipleTransactionsParams.categoryId) &&
        Objects.equals(this.labelIds, updateMultipleTransactionsParams.labelIds) &&
        Objects.equals(this.ids, updateMultipleTransactionsParams.ids) &&
        Objects.equals(this.accountIds, updateMultipleTransactionsParams.accountIds);
  }

  @Override
  public int hashCode() {
    return Objects.hash(isNew, isPotentialDuplicate, categoryId, labelIds, ids, accountIds);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UpdateMultipleTransactionsParams {\n");
    
    sb.append("    isNew: ").append(toIndentedString(isNew)).append("\n");
    sb.append("    isPotentialDuplicate: ").append(toIndentedString(isPotentialDuplicate)).append("\n");
    sb.append("    categoryId: ").append(toIndentedString(categoryId)).append("\n");
    sb.append("    labelIds: ").append(toIndentedString(labelIds)).append("\n");
    sb.append("    ids: ").append(toIndentedString(ids)).append("\n");
    sb.append("    accountIds: ").append(toIndentedString(accountIds)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

