/**
 * Multibanking REST Api
 * Use a bank code (blz) ending with X00 000 00 like 300 000 00 to run aggainst the mock backend. Find the mock backend at ${hostname}:10010
 *
 * OpenAPI spec version: 5.1.3-SNAPSHOT
 * Contact: age@adorsys.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { BookingPeriodTO } from './bookingPeriodTO';
import { ContractTO } from './contractTO';


export interface BookingGroupTO { 
    amount?: number;
    bookingPeriods?: Array<BookingPeriodTO>;
    contract?: ContractTO;
    mainCategory?: string;
    name?: string;
    otherAccount?: string;
    salaryWage?: boolean;
    specification?: string;
    subCategory?: string;
    type?: BookingGroupTO.TypeEnum;
}
export namespace BookingGroupTO {
    export type TypeEnum = 'STANDING_ORDER' | 'RECURRENT_INCOME' | 'RECURRENT_SEPA' | 'RECURRENT_NONSEPA' | 'CUSTOM' | 'OTHER_INCOME' | 'OTHER_EXPENSES';
    export const TypeEnum = {
        STANDINGORDER: 'STANDING_ORDER' as TypeEnum,
        RECURRENTINCOME: 'RECURRENT_INCOME' as TypeEnum,
        RECURRENTSEPA: 'RECURRENT_SEPA' as TypeEnum,
        RECURRENTNONSEPA: 'RECURRENT_NONSEPA' as TypeEnum,
        CUSTOM: 'CUSTOM' as TypeEnum,
        OTHERINCOME: 'OTHER_INCOME' as TypeEnum,
        OTHEREXPENSES: 'OTHER_EXPENSES' as TypeEnum
    };
}
