export enum GroupType {
    STANDING_ORDER = <any>'STANDING_ORDER',
    RECURRENT_INCOME = <any>'RECURRENT_INCOME',
    RECURRENT_SEPA = <any>'RECURRENT_SEPA',
    RECURRENT_NONSEPA = <any>'RECURRENT_NONSEPA',
    CUSTOM = <any>'CUSTOM',
    OTHER_INCOME = <any>'OTHER_INCOME',
    OTHER_EXPENSES = <any>'OTHER_EXPENSES'
}