HTTP/1.1 200 OK
Server: Apache/1.3.29 (Unix) PHP/4.3.4
Connection: close
Content-Type: application/json

{
  "transactionsDetails": {
    "transactionId": "12345678",
    "debtorName": "Johann Kilometer",
    "debtorAccount": {
      "iban": "DE08154711"
    },
    "mandateId": "Mandate-XYZ",
    "transactionAmount": {
      "currency": "EUR",
      "amount": "550.00"
    },
    "bookingDate": "2017-10-25",
    "valueDate": "2017-10-26",
    "remittanceInformationUnstructured": "Example 1",
    "bankTransactionCode": "PMNT-RDDT-ESDD"
  }
}
