HTTP/1.1 200 OK
Server: Apache/1.3.29 (Unix) PHP/4.3.4
Connection: close
Content-Type: application/json

{
  "account": {
    "iban": "******",
    "currency": "******"
  },
  "transactions": {
    "booked": [
      {
        "endToEndId": "e6",
        "mandateId": "m6",
        "bookingDate": "2020-01-01",
        "valueDate": "2020-01-01",
        "transactionAmount": {
          "currency": "EUR",
          "amount": "500.02"
        },
        "creditorName": "Hansdampf",
        "creditorAccount": {
          "iban": "Iban"
        },
        "ultimateCreditor": "******",
        "debtorName": "******",
        "debtorAccount": {
          "iban": "Iban2"
        },
        "remittanceInformationUnstructured": "******",
        "purposeCode": "******",
        "proprietaryBankTransactionCode": "******"
      }
    ],
    "pending": [
      {
        "endToEndId": "e2e",
        "mandateId": "mid",
        "bookingDate": "2020-01-01",
        "valueDate": "2020-01-01",
        "transactionAmount": {
          "currency": "EUR",
          "amount": "-250"
        },
        "creditorName": "Hansdampf",
        "creditorAccount": {
          "iban": "Iban"
        },
        "ultimateCreditor": "******",
        "debtorName": "******",
        "debtorAccount": {
          "iban": "Iban2"
        },
        "remittanceInformationUnstructured": "******",
        "purposeCode": "******",
        "proprietaryBankTransactionCode": "******"
      },
      {
        "endToEndId": "e3e",
        "mandateId": "m3d",
        "bookingDate": "2020-01-01",
        "valueDate": "2020-01-01",
        "transactionAmount": {
          "currency": "EUR",
          "amount": "300"
        },
        "creditorName": "Hansdampf",
        "creditorAccount": {
          "iban": "Iban"
        },
        "ultimateCreditor": "******",
        "debtorName": "******",
        "debtorAccount": {
          "iban": "Iban2"
        }
       }
    ],
    "_links": {
      "account": {
        "href": "******"
      },
     "next": {
       "href": "http://localhost:1234/v1/account/xxx/transactions?page=6"
     }
    }
  },
  "balances": [
    {
      "balanceType": "expected",
      "balanceAmount": {
        "amount": "4100.02",
        "currency": "EUR"
      }
    },
    {
      "balanceType": "forwardAvailable",
      "balanceAmount": {
        "amount": "27.40",
        "currency": "EUR"
      }
    }
  ]
}
