FROM docker.io/jboss/keycloak-postgres

USER root

# GET keycloak-custom-secret-provider
RUN curl -s -L --insecure "http://central.maven.org/maven2/de/adorsys/multibanking/keycloak-custom-secret-provider/1.6/keycloak-custom-secret-provider-1.6.jar" > /opt/jboss/keycloak/providers/keycloak-custom-secret-provider.jar

# Customize Wildfly standalone-*.xml
ADD keycloak-customization.xsl /opt/jboss/keycloak/
RUN java -jar /usr/share/java/saxon.jar -s:/opt/jboss/keycloak/standalone/configuration/standalone.xml -xsl:/opt/jboss/keycloak/keycloak-customization.xsl -o:/opt/jboss/keycloak/standalone/configuration/standalone.xml; java -jar /usr/share/java/saxon.jar -s:/opt/jboss/keycloak/standalone/configuration/standalone-ha.xml -xsl:/opt/jboss/keycloak/customization.xsl -o:/opt/jboss/keycloak/standalone/configuration/standalone-ha.xml; rm /opt/jboss/keycloak/keycloak-customization.xsl

USER jboss